POST http://localhost:8080/init HTTP/1.1
content-type: application/json

{
  "value": {
    "__ow_action_name" : "nodejs-web-action-set-a-cookie",
    "main" : "main",
    "binary": false,
    "code" : "function main() { return { headers: { 'Set-Cookie': 'UserID=Jane; Max-Age=3600; Version=', 'Content-Type': 'text/html'}, statusCode: 200, body: '<html><body><h3>hello</h3></body></html>' }}"
  }
}

###
