POST http://localhost:8080/init HTTP/1.1
content-type: application/json

{
  "value": {
    "name" : "nodejs-helloworld",
    "main" : "main",
    "binary": false,
    "code" : "function main() {return {payload: 'Hello World!'};}"
  }
}

###
