OPTIONS http://localhost:8080/ HTTP/1.1
content-type: application/json

{
  "init": {
    "name" : "nodejs-web-action-options",
    "main" : "main",
    "binary": false,
    "code" : "function main(params) { if (params.__ow_method == 'OPTIONS') { return { headers: { 'Access-Control-Allow-Methods': 'OPTIONS, GET', 'Access-Control-Allow-Origin': 'example.com' }, statusCode: 200 }}}"
  },
  "activation": {
    "namespace": "default",
    "action_name": "nodejs-web-action-options",
    "api_host": "",
    "api_key": "",
    "activation_id": "",
    "deadline": "4102498800000"
  },
  "value": {
    "name": "Joe"
  }
}

###
