POST http://localhost:8080/run HTTP/1.1
content-type: application/json

{
  "value": {
  },
  "namespace": "default",
  "action_name": "java-helloworld",
  "api_host": "",
  "api_key": "",
  "activation_id": "",
  "deadline": "4102498800000"
}

###
